ECommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('category/', include('category.urls')),
    path('', include('product.urls')),
    path('order/', include('order.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns_api = [
    path('api/v1/', include('category.api.urls')),
    path('api/v1/', include('product.api.urls')),
    path('api/v1/', include('order.api.urls')),
]

urlpatterns += urlpatterns_api

order/api/urls.py
from django.urls import path

from order.api.views import OrderList, OrderAddView, RemoveOrderView, OrderItemIncrementApiView, OrderItemDecrementApiView

urlpatterns = [
    path('order/', OrderList.as_view(), name='order-list'),
    path('order/add/<int:pk>', OrderAddView.as_view(), name='order-add'),
    path('order/remove/<int:pk>', RemoveOrderView.as_view(), name='order-remove'),
    path('order/increment/<int:pk>', OrderItemIncrementApiView.as_view(), name='order-increment'),
    path('order/decrement/<int:pk>', OrderItemDecrementApiView.as_view(), name='order-decrement'),
]

order/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    order_summary
)

app_name = 'order'

urlpatterns = [
    path('order-summary', order_summary, name='order_summary'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item')
]

order/models.py
from django.db import models

from base.models import TimeStampedModel
from account.models import User
from product.models import Product


class OrderItem(TimeStampedModel):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orderitem')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orderitem')
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quantity} * {self.product.price} = {self.total_price}'

    def calc_price(self):
       return self.quantity * self.product.price

    def save(self, *args, **kwargs):
        self.total_price = self.calc_price()
        return super(OrderItem, self).save(*args, **kwargs)


class Order(TimeStampedModel):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order')
    orderitem = models.ManyToManyField(OrderItem)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.total_price}'

    def calc_total(self):
        total = 0
        for orderitem in self.orderitem.objects.all():
            total += orderitem.total_price
        return total

    # def save(self, *args, **kwargs):
    #     self.total_price = self.calc_total()
    #     return super(Order, self).save(*args, **kwargs)

order/api/views.py
from django.db.models import F
from django.shortcuts import get_object_or_404

from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework import permissions
from rest_framework.response import Response

from order.api.permission import OrderPermission, OrderItemAuthorPermission
from order.api.serializers import OrderSerializer, OrderItemSerializer
from order.models import Order, OrderItem
from product.models import Product


class OrderList(generics.ListAPIView):
    serializer_class = OrderSerializer
    queryset = Order.objects.all()


class OrderAddView(generics.CreateAPIView):
    serializer_class = OrderItemSerializer
    permission_classes = [permissions.IsAuthenticated, OrderPermission]

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        self.check_object_permissions(self.request, product)
        if product.quantity <= 0:
            return Response({"message": "product qolmadi"}, status=status.HTTP_200_OK)
        order, created = Order.objects.get_or_create(customer=request.user, ordered=False)
        orderitem, item_created = OrderItem.objects.get_or_create(product=product, customer=request.user, ordered=False)
        if not item_created:
            orderitem.quantity = F('quantity') + 1
            product.quantity = F('quantity') - 1
        else:
            order.ordered.add(orderitem)
            product.quantity = F('quantity') - 1

        return Response({'message': 'Ok'}, status=status.HTTP_201_CREATED)


class RemoveOrderView(APIView):
    permission_classes = [permissions.IsAuthenticated, OrderItemAuthorPermission]

    def post(self, request, pk):
        orderitem = get_object_or_404(OrderItem, pk=pk)
        order = Order.objects.filter(orderitem=orderitem, ordered=False).first()
        self.check_object_permissions(self.request, orderitem)
        orderitem.product.quantity + F('orderitem.quantity')
        order.orderitem.remove(orderitem)
        orderitem.delete()
        return Response({'message': 'ok'}, status=status.HTTP_204_NO_CONTENT)


class OrderItemIncrementApiView(APIView):
    permission_classes = [permissions.IsAuthenticated, OrderItemAuthorPermission]

    def post(self, request, pk):
        orderitem = get_object_or_404(OrderItem, pk=pk)
        self.check_object_permissions(self.request, orderitem)
        if orderitem.product.quantity <= 0:
            return Response({"message": "product qolmadi"}, status=status.HTTP_200_OK)
        orderitem.quantity = F('quantity') + 1
        orderitem.save()
        orderitem.product.quantity = F('quantity') - 1
        orderitem.product.save()
        return Response({'message': 'ok'}, status=status.HTTP_200_OK)


class OrderItemDecrementApiView(APIView):
    permission_classes = [permissions.IsAuthenticated, OrderItemAuthorPermission]

    def post(self, request, pk):
        orderitem = get_object_or_404(OrderItem, pk=pk)
        self.check_object_permissions(self.request, orderitem)
        if orderitem.quantity == 1:
            orderitem.product.quantity = F('quantity') + 1
            orderitem.delete()
            return Response({"message": "Order delete"}, status=status.HTTP_204_NO_CONTENT)
        orderitem.quantity = F('quantity') + 1
        orderitem.save()
        orderitem.product.quantity = F('quantity') + 1
        orderitem.product.save()
        return Response({'message': 'ok'}, status=status.HTTP_200_OK)

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from .models import (
    Order,
    OrderItem
)

from .tasks import send_email
from product.models import Product


@login_required(login_url='/accounts/login/')
def order_summary(request):

    order = Order.objects.filter(customer=request.user, ordered=False).annotate(
        order_total_price=Sum('orderitem__total_price')
    ).first()
    context = {
        'order': order
    }

    return render(request, 'order/cart.html', context)




@login_required
def add_to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order_item, created = OrderItem.objects.get_or_create(
        product=product,
        customer=request.user,
        ordered=False
    )

    order_qs = Order.objects.filter(customer=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.orderitem.filter(product__pk=product.pk).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Added quantity Item")
            return redirect("order:order_summary")
        else:
            order.orderitem.add(order_item)
            messages.info(request, "Item added to your cart")
            return redirect("order:order_summary")
    else:
        order = Order.objects.create(customer=request.user)
        order.orderitem.add(order_item)
        send_email.delay(order.id)
        messages.info(request, "Item added to your cart")
        return redirect("order:order_summary")


@login_required
def remove_from_cart(request, pk):
    order_item = OrderItem.objects.get(pk=pk)
    order = order_item.order_set.all().first()
    if order:
        order.orderitem.remove(order_item)
        order_item.delete()
    return redirect("order:order_summary")


@login_required
def reduce_quantity_item(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)
    order = Order.objects.filter(
        customer=request.user,
        ordered=False
    ).first()
    if order:
        if order_item:
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.orderitem.remove(order_item)
                order_item.delete()
            messages.info(request, "Item quantity was updated")
            return redirect("order:order_summary")
        else:
            messages.info(request, "This Item not in your cart")
            return redirect("order:order_summary")
    else:
        # add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("order:order_summary")

templates/order/cart.html
category_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Cart {% endblock %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->

        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                        <tr class="small text-uppercase">
                            <th scope="col">Product</th>
                            <th scope="col" width="120">Quantity</th>
                            <th scope="col" width="120">Price</th>
                            <th scope="col" class="text-right" width="200"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for orderitem in order.orderitem.all %}
                        <tr>
                            <td>
                                <figure class="itemside align-items-center">
                                    <div class="aside"><img src="./images/items/11.jpg" class="img-sm"></div>
                                    <figcaption class="info">
                                        <a href="#" class="title text-dark">{{ orderitem.product.title }}</a>
                                        <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                                    </figcaption>
                                </figure>
                            </td>
                            <td>
                                <!-- col.// -->
                                <div class="col">
                                    <div class="input-group input-spinner">
                                        <div class="input-group-prepend">
                                            <a href="{% url 'order:reduce-quantity-item' orderitem.pk %}" class="btn btn-light" type="button" id="button-plus"><i
                                                    class="fa fa-minus"></i></a>
                                        </div>
                                        <input type="text" class="form-control" value="{{ orderitem.quantity }}">
                                        <div class="input-group-append">
                                            <a href="" class="btn btn-light" type="button" id="button-minus"><i
                                                    class="fa fa-plus"></i></a>
                                        </div>
                                    </div> <!-- input-group.// -->
                                </div> <!-- col.// -->
                            </td>
                            <td>
                                <div class="price-wrap">
                                    <var class="price">${{ orderitem.total_price }}</var>
                                    <small class="text-muted"> ${{ orderitem.product.price }} each </small>
                                </div> <!-- price-wrap .// -->
                            </td>
                            <td class="text-right">
                                <a href="{% url 'order:remove-from-cart' orderitem.pk %}" class="btn btn-danger"> Remove</a>
                            </td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">${{ order.order_total_price }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> $10.00</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="./images/misc/payments.png" height="26">
                        </p>
                        <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                        <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>

{% endblock %}